---
# Source perlbrew's bashrc and update our Ansible environment
# Note: Doesn't really remove ~/bashrc - ansible will only run though if
#       bashrc file exists

- name: Set perlbrew environment variables
  shell: >
    source ~/{{ perl_major_version }}/perlbrew/etc/bashrc &&
    printenv | sort
    removes=~/{{ perl_major_version }}/perlbrew/etc/bashrc
  register: perlbrewlib_env
  failed_when: no
  args:
    executable: /bin/bash

- set_fact:
    perlbrew_env: "{{ perlbrewlib_env | getenvs }}"
  when: perlbrewlib_env.changed
